all:
	@gcc -g -Wall -Wextra -Werror ${SRC_FILES} -I../../include -o builtins

SRC_FILES = builtins.c builtins_export.c builtins_export_print.c builtins_utils.c

#test:
#	@./tokenizer_tester.sh

.PHONY: all test